version: "3"

services:
  app:
    container_name: covid-tracker
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
